add check for updating bd_scan to new version

diff --git a/.github/workflows/blackduck.yml b/.github/workflows/blackduck.yml
--- a/.github/workflows/blackduck.yml
+++ b/.github/workflows/blackduck.yml
@@ -35,6 +35,10 @@ jobs:
             echo "Error: DETECT_PROJECT_VERSION_NAME is not updated in bd_scan.sh script."
             exit 1
           fi
+          if [ "$(printf '%s\n' "$LATEST_VERSION" "$CURRENT_VERSION" | sort -V | head -n 1)" != "$CURRENT_VERSION" ]; then
+            echo "Error: DETECT_PROJECT_VERSION_NAME ($CURRENT_VERSION) is not updated to the latest version in bd_scan.sh script)."
+            exit 1
+          fi
 
   build:
     needs: validate-version
